### ISSUE TITLE
UI is R/W accessible to the public

### ISSUE THREAD

**Issue by jpluscplusm** [EngineerBetter/byo-service-mesh#1]
Currently the route `https://eb-consul.cfapps.io/` allows public R/W access. This might want to be tightened up, not only for the security of this cluster, but of anyone borrowing it as a starting point.

Without that, who knows /what/ could get thrown into the KV store ...

**Comment by andy-paine** [comment]
Surely the cutest way to disclose a security issue! Apps are now stopped 🐶
